#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Prepare dataset for continual RL pre-training and conversational LLM (-instruct) reasoning
"""

import argparse
import json
import math
import os
import time
# 该脚本纯粹是为了补全数据
import os
import json
import sys
from tqdm import tqdm
from string import Template
from collections import defaultdict
from transformers import AutoTokenizer
from typing import Dict, List, Union

abs_path = "/workspace/"
TOKENIZER_NAME = abs_path + "qwen3-train/models/instruct-6.7b"
INPUT_DIR = abs_path + "trl-main/datasets/test/eval_exebench_data.jsonl"  # 输入数据的绝对路径，包含所有的jsonl文件
OUTPUT_FILE = abs_path + "trl-main/datasets/test/TestEBRef.jsonl"  # 或者 TestEBRef.jsonl # 输出数据的文件夹地址，和in_path一级
MAX_LEN = 4096


def is_empty_dict(d):
    return isinstance(d, dict) and not d


def prompt4chat4ref(datapoint): # 该prompt中没有添加info
    pscode = datapoint['pscode'] # ida产生的反汇编代码，只有一个cfg block，没有图

    prompt4input = Template("""Please understand the provided pseudocode, and decompile it into the corresponding high-level C source code.

    - The pseudocode:
    ```
    $pscode
    ```

    The high-level C source code is: """)
    rprompt4input = Template.substitute(prompt4input, pscode=pscode)

    return rprompt4input

def chatmessage(datapoint):
    user_content = prompt4chat4ref(datapoint)
    system_message = {
        "role": "system",
        "content": "You are a decompilation expert. Your task is to analyze the pseudocode generated by the existing decompilation tool, and generate accurate high-level C source code. The generated C code must have: 1) Correct program logic and control flow structure. 2) Properly typed and named functions. 3) Properly typed and named variables and data. 4) Standard, readable syntax."
    }

    messages = [
        system_message,
        {"role": "user", "content": user_content},
        # {"role": "assistant", "content": datapoint["sourcecode"]} # 推理时不需要
    ]

    # 返回符合 Qwen3 chat 格式的数据
    return {
        "prompt": messages,
        "source": datapoint["sourcecode"],
        "dependency": datapoint["dependencies"],
        "orig_data": {k: v for k, v in datapoint.items() if k != "sourcecode" and k != "dependencies"},
    }




def dict_to_string(data: Union[Dict, List], indent: int = 0) -> str:
    """Convert dictionary/list to a formatted string representation."""
    if isinstance(data, dict):
        lines = []
        for key, value in data.items():
            if isinstance(value, (dict, list)):
                lines.append(f"{'  ' * indent}{key}:")
                lines.append(dict_to_string(value, indent + 1))
            else:
                lines.append(f"{'  ' * indent}{key}: {value}")
        return '\n'.join(lines)
    elif isinstance(data, list):
        lines = []
        for i, item in enumerate(data):
            if isinstance(item, (dict, list)):
                lines.append(f"{'  ' * indent}[{i}]:")
                lines.append(dict_to_string(item, indent + 1))
            else:
                lines.append(f"{'  ' * indent}[{i}]: {item}")
        return '\n'.join(lines)
    else:
        return str(data)


def count_tokens_simple(tokenizer, data) -> int:
    """Count tokens in a text string."""
    text = dict_to_string(data)
    if not text or not isinstance(text, str):
        return 0

    tokens = tokenizer.encode(text, add_special_tokens=False)
    return len(tokens)


def load_tokenizer():
    print(f"Loading tokenizer: {TOKENIZER_NAME}")
    return AutoTokenizer.from_pretrained(TOKENIZER_NAME, trust_remote_code=True)




def process_jsonl_folder(in_folder_path, output_file):
    tokenizer = load_tokenizer()  # get the tokenizer
    # output_file = os.path.join(out_folder_path, f"rl_data.jsonl")
    open(output_file, "w", encoding="utf-8").close()
    data_count = 0

    if os.path.isfile(in_folder_path):
        jsonl_files = [in_folder_path]
    else:
        jsonl_files = [f for f in os.listdir(in_folder_path) if f.endswith(".jsonl")]
    file_count = len(jsonl_files)
    # for filename in tqdm(jsonl_files, desc="处理文件", unit="file", leave=False):
    for i, filename in enumerate(tqdm(jsonl_files, desc="处理文件", unit="file", leave=False)):
        input_path = os.path.join(in_folder_path, filename)
        with open(input_path, "r", encoding="utf-8") as infile, \
                open(output_file, "a", encoding="utf-8") as outfile:

            for line in infile:
                line = line.strip()
                if not line:
                    continue

                try:
                    obj = json.loads(line)
                    if obj.get("mode") == "64":
                        if "pscode" in obj:
                            obj_str = obj['pscode']
                            if isinstance(obj_str, str) and obj_str.strip():
                                processed_obj = chatmessage(obj)
                                token_len = count_tokens_simple(tokenizer, processed_obj["prompt"])
                                if token_len >= MAX_LEN:
                                    continue
                                json.dump(processed_obj, outfile, ensure_ascii=False)
                                outfile.write("\n")
                                data_count += 1
                            else:
                                print("There is no pscode for this data! It is an error!")
                        else:
                            print("There is no pscode for this data! It is an error!")
                except json.JSONDecodeError as e:
                    print(f"跳过无法解析的行 in {filename}: {e}")

        print(f"已经处理完第 {i+1}/{file_count} 个文件")
    print(f"所有文件已处理完毕，一共有 {data_count} 条数据！")


def get_subfolders(folder_path):
    """获取文件夹下的所有子文件夹"""
    if not os.path.exists(folder_path):
        print(f"文件夹不存在: {folder_path}")
        return []

    subfolders = []
    for item in os.listdir(folder_path):
        item_path = os.path.join(folder_path, item)
        if os.path.isdir(item_path):
            subfolders.append(item_path)

    return subfolders

if __name__ == "__main__":
    process_jsonl_folder(INPUT_DIR, OUTPUT_FILE)
